function y = untitled(x)
%UNTITLED 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 13-May-2025 16:46:43

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    % % IIR Least P-th norm Bandpass filter designed using the IIRLPNORM
    % % function.
    %
    % % All frequency values are in Hz.
    % Fs = 48000;  % Sampling Frequency
    %
    % Nb     = 8;        % Numerator Order
    % Na     = 8;        % Denominator Order
    % Fstop1 = 7200;     % First Stopband Frequency
    % Fpass1 = 9600;     % First Passband Frequency
    % Fpass2 = 12000;    % Second Passband Frequency
    % Fstop2 = 14400;    % Second Stopband Frequency
    % Wstop1 = 1;        % First Stopband Weight
    % Wpass  = 1;        % Passband Weight
    % Wstop2 = 1;        % Second Stopband Weight
    % P      = [2 128];  % P'th norm
    % dens   = 20;       % Density Factor
    %
    % F = [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2);
    %
    % % Calculate the coefficients using the IIRLPNORM function.
    % [b,a,err,sos_var,g] = iirlpnorm(Nb, Na, F, F, [0 0 1 1 0 0], [Wstop1 ...
    %                                 Wstop1 Wpass Wpass Wstop2 Wstop2], P, ...
    %                                 {dens});
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.23298971685946 0.999926862134551 1 ...
        -0.647791706397658 0.912379736818116; 1 0.682761054211822 ...
        0.988009682749857 1 -0.422720427118715 0.778043703158563; 1 ...
        1.49149836699174 0.876048665746013 1 -0.126758712432246 ...
        0.778263582929123; 1 -2.03041481595456 1.02361798901556 1 ...
        0.0606756956800452 0.912613585237761], ...
        'ScaleValues', [0.00330722346707444; 1; 1; 1; 1]);
end

y = step(Hd,double(x));


% [EOF]
