function y = FIR_lowpass_doFilter(x)
%DOFILTER 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 14-May-2025 08:49:56

persistent Hd;

if isempty(Hd)
    
    N     = 200;     % Order
    Fpass = 200000;  % Passband Frequency
    Fstop = 205000;  % Stopband Frequency
    Apass = 0.1;     % Passband Ripple (dB)
    Fs    = 450000;  % Sampling Frequency
    
    h = fdesign.lowpass('n,fp,fst,ap', N, Fpass, Fstop, Apass, Fs);
    
    Hd = design(h, 'equiripple');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

