function Hd = FIR_lowpass_returnFilter
%GETFILTER 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 14-May-2025 08:59:31

N     = 200;     % Order
Fpass = 200000;  % Passband Frequency
Fstop = 205000;  % Stopband Frequency
Apass = 0.1;     % Passband Ripple (dB)
Fs    = 450000;  % Sampling Frequency

h = fdesign.lowpass('n,fp,fst,ap', N, Fpass, Fstop, Apass, Fs);

Hd = design(h, 'equiripple');


